name: Setup Python
on:
  workflow_call:

jobs:
  cache:
    runs-on: ${{ inputs.runner || 'ubuntu-latest' }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'