name: Setup Python
description: Setup Python for CI
inputs:
  python-version:
    description: Python version
    required: false
    default: '3.13.5'
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
