---
name: Build and Push Docker Image to Google Cloud Platform
on:
  push:
    branches: [ master ]

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: iva-prime
      PROJECT_ID: iva-prime
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: "auth"
      name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        service_account: 'github-actions@iva-prime.iam.gserviceaccount.com'

    - name: Change to docker directory
      working-directory: ./docker
      run: echo "Changed to docker directory"

    - id: "deploy"
      working-directory: ./docker
      run: |
        gcloud config set project iva-prime
        gcloud app deploy --format json app.yaml --project iva-prime --promote --no-cache

    - name: Delete old and unsued App Engine versions (0% traffic only)
      run: |
        echo "Deleting App Engine versions."
        gcloud app versions list \
          --format="value(version.id)" \
          --filter="traffic_split=0.0" | \
        xargs -r gcloud app versions delete -q