name: Build Tauri App

run-name: >
  ${{ github.event_name == 'schedule' && 'Nightly Build - ' || 
      github.event_name == 'release' && 'Release Build - ' || 
      github.event_name == 'workflow_dispatch' && (github.ref == 'refs/heads/master' && 'Manual Pre-Release Build - ' || 'Manual Build - ') || 
      github.event_name == 'pull_request' && 'PR Build - ' || 
      'Build' 
  }}
  ${{ github.ref_name }} by @${{ github.actor }}

on:
  workflow_dispatch: # Manual trigger: on PR -> no pre-release or on master -> pre-release
  schedule: # Nightly build
    - cron: '0 0 * * *'
  pull_request: # PR
    branches:
      - master
  release: # Full release
    types: [published]


jobs:
  get-info:
    name: Get Info
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      should_build: ${{ steps.decide_should_build.outputs.should_build }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from Cargo.toml and context
        id: get_version
        working-directory: tauri/iva-prime/src-tauri
        shell: bash
        run: |
          VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml)
          if [ "${{ github.event_name }}" = "release" ]; then
            FINAL_VERSION="$VERSION"
          else
            FINAL_VERSION="$VERSION-pre-release-${{ github.run_id }}"
          fi
          echo "version=$FINAL_VERSION" >> $GITHUB_OUTPUT
          echo "version=$FINAL_VERSION"

  
      - name: Decide whether to build
        id: decide_should_build
        run: |
          echo "GitHub event: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" = "schedule" ]; then
            sudo apt-get update && sudo apt-get install -y gh jq
            LAST_RUN=$(gh run list --repo "${{ github.repository }}" --workflow="Build Tauri App" --branch=master --event=schedule --json startedAt,status,conclusion --limit 10 | jq -r '[.[] | select(.status=="completed" and .conclusion=="success")][0].startedAt')
            echo "Last successful scheduled run: $LAST_RUN"
            if [ -z "$LAST_RUN" ] || [ "$LAST_RUN" == "null" ]; then
              echo "should_build=true" >> $GITHUB_OUTPUT
              echo "No previous run -> build"
              exit 0
            fi
            COMMITS=$(gh api repos/${{ github.repository }}/commits -F sha=master -F since="$LAST_RUN" | jq 'length')
            echo "Number of new commits: $COMMITS"
            if [ "$COMMITS" -gt "0" ]; then
              echo "should_build=true" >> $GITHUB_OUTPUT
              echo "New commits -> build"
            else
              echo "should_build=false" >> $GITHUB_OUTPUT
              echo "No new commits since last scheduled run -> skipping build"
              exit 0
            fi
          else
            echo "Non-scheduled run (PR, dispatch, release, etc) -> always build"
            echo "should_build=true" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    needs: [get-info]
    if: needs.get-info.outputs.should_build == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Runner
        uses: ./.github/actions/setup-runner
        with:
          version: ${{ needs.get-info.outputs.version }}

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: tauri/iva-prime
          args: >-
            --bundles nsis -c '{"version": "${{ needs.get-info.outputs.version }}"}'

      - name: Rename and Upload Windows artifact
        uses: ./.github/actions/rename-and-upload-artifacts
        with:
          targets: |
            .exe -> release/bundle/nsis/ -> win64-setup
            .exe.sig -> release/bundle/nsis/ -> win64-setup
          version: ${{ needs.get-info.outputs.version }}
          artifact-name: iva-prime-windows


  build-macos-intel:
    name: Build for macOS Intel CPUs
    runs-on: macos-latest
    needs: [get-info]
    if: needs.get-info.outputs.should_build == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Runner
        uses: ./.github/actions/setup-runner
        with:
          rust-targets: x86_64-apple-darwin
          version: ${{ needs.get-info.outputs.version }}

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: tauri/iva-prime
          args: >-
            --target x86_64-apple-darwin --bundles app,dmg -c '{"version": "${{ needs.get-info.outputs.version }}"}'

      - name: Rename and Upload macOS Intel artifact
        uses: ./.github/actions/rename-and-upload-artifacts
        with:
          targets: |
            .app.tar.gz -> x86_64-apple-darwin/release/bundle/macos/ -> macos-intel
            .app.tar.gz.sig -> x86_64-apple-darwin/release/bundle/macos/ -> macos-intel
            .dmg -> x86_64-apple-darwin/release/bundle/dmg/ -> macos-intel
          version: ${{ needs.get-info.outputs.version }}
          artifact-name: iva-prime-macos-intel


  build-macos-arm:
    name: Build for macOS ARM CPUs
    runs-on: macos-latest
    needs: [get-info]
    if: needs.get-info.outputs.should_build == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Runner
        uses: ./.github/actions/setup-runner
        with:
          rust-targets: aarch64-apple-darwin
          version: ${{ needs.get-info.outputs.version }}

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: tauri/iva-prime
          args: >-
            --target aarch64-apple-darwin --bundles app,dmg -c '{"version": "${{ needs.get-info.outputs.version }}"}'

      - name: Rename and Upload macOS ARM artifact
        uses: ./.github/actions/rename-and-upload-artifacts
        with:
          targets: |
            .app.tar.gz -> aarch64-apple-darwin/release/bundle/macos/ -> macos-arm
            .app.tar.gz.sig -> aarch64-apple-darwin/release/bundle/macos/ -> macos-arm
            .dmg -> aarch64-apple-darwin/release/bundle/dmg/ -> macos-arm
          version: ${{ needs.get-info.outputs.version }}
          artifact-name: iva-prime-macos-arm


  build-linux:
    name: Build for Linux
    runs-on: ubuntu-22.04
    needs: [get-info]
    if: needs.get-info.outputs.should_build == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Runner
        uses: ./.github/actions/setup-runner
        with:
          version: ${{ needs.get-info.outputs.version }}

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: tauri/iva-prime
          args: >-
            --bundles appimage,deb,rpm -c '{"version": "${{ needs.get-info.outputs.version }}"}'

      - name: Rename and Upload Linux artifact
        uses: ./.github/actions/rename-and-upload-artifacts
        with:
          targets: |
            .AppImage -> release/bundle/appimage/ -> linux
            .AppImage.sig -> release/bundle/appimage/ -> linux
            .deb -> release/bundle/deb/ -> linux
            .deb.sig -> release/bundle/deb/ -> linux
            .rpm -> release/bundle/rpm/ -> linux
            .rpm.sig -> release/bundle/rpm/ -> linux
          version: ${{ needs.get-info.outputs.version }}
          artifact-name: iva-prime-linux



  pre-release:
    name: Create Pre-release
    runs-on: ubuntu-latest
    needs: [get-info, build-windows, build-macos-intel, build-macos-arm, build-linux]
    if: (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master') || (github.event_name == 'schedule' && needs.get-info.outputs.should_build == 'true')
    steps:
      - name: Prepare Pre-release Artifacts
        id: prepare
        uses: ./.github/actions/prepare-release
        with:
          version: ${{ needs.get-info.outputs.version }}
          nightly: "true"


      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: "IVA Prime v${{ needs.get-info.outputs.version }}"
          prerelease: true
          body: |
            Nightly build of the IVA Prime desktop app.
            This version might contain bugs and can be unstable compared to the full release!
          files: ${{ steps.prepare.outputs.files_list }}


  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [get-info, build-windows, build-macos-intel, build-macos-arm, build-linux]
    if: github.event_name == 'release'
    steps:
      - name: Prepare Release Artifacts
        id: prepare
        uses: ./.github/actions/prepare-release
        with:
          version: ${{ needs.get-info.outputs.version }}
          nightly: "false"

      - name: Upload assets to GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.prepare.outputs.files_list }}
        
